version: '3.8'

services:
  # Blockchain Core
  blockchain-core:
    build: ./blockchain-core
    container_name: elizaicoin-blockchain-core
    ports:
      - "5000:5000"
    volumes:
      - blockchain_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/stats"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  # Redis Cache
  redis:
    image: redis:alpine
    container_name: elizaicoin-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Explorer Backend
  explorer-backend:
    build: ./explorer-backend
    container_name: elizaicoin-explorer-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - BLOCKCHAIN_API_URL=http://blockchain-core:5000
      - REDIS_URL=redis://redis:6379
    depends_on:
      - blockchain-core
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  # Explorer Frontend
  explorer-frontend:
    build: ./explorer-frontend
    container_name: elizaicoin-explorer-frontend
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://localhost:3000/api
    depends_on:
      - explorer-backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  # Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:latest
    container_name: elizaicoin-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    restart: unless-stopped
    depends_on:
      - explorer-backend

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: elizaicoin-grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    restart: unless-stopped
    depends_on:
      - prometheus

volumes:
  blockchain_data:
  redis_data:
  prometheus_data:
  grafana_data:
